myapp/urls.py
from django.conf.urls import url
from django.contrib.auth import logout
from django.urls import path
from .views import home, delete, loginPAGE, logoutPAGE, pages, register
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    path('',register,name='register'),
    path('login/',loginPAGE,name='login'),
    path('logout/',logoutPAGE,name='logout'),


    path('home/',home,name='home'),
    path('page/<int:pk>/',pages,name='page'),
    path('delete/<int:pk>',delete,name='delete'),


    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='accounts/reset.html'),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/reset_done.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/confirm.html'),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/complete.html'),name="password_reset_complete"),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('qrcode-admin/', admin.site.urls),
    path('',include('myapp.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image,ImageDraw
from django.contrib.auth.models import User

class YourModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    url = models.TextField()
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True)
    color  = models.CharField(max_length=255,null=True, blank=True)

    
    def save(self, *args, **kwargs):
        qr_code_img = qrcode.QRCode()
        qr_code_img.add_data(self.url)
        canvas = qr_code_img.make_image(fill_color=self.color)
        fname = f"qr_code-{self.title}"+".png"
        buffer = BytesIO()
        canvas.save(buffer,"PNG")
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args,**kwargs)

myapp/forms.py
from django import forms
from .models import YourModel
class YOurMOdelForm(forms.ModelForm):
    class Meta:
        model = YourModel
        fields = "__all__"

myapp/views.py
from django.db import models
from django.shortcuts import redirect, render
from .models import YourModel
from .forms import YOurMOdelForm
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.validators import URLValidator
# Create your views here.

@login_required(login_url='login')
def home(request):
    model = YourModel()
    form = YOurMOdelForm(request.POST,request.FILES,instance=model)
    print(request.POST)
    if form.is_valid():
        form.save()
        return redirect('home')
    qr_code = YourModel.objects.order_by('-id').filter(user=request.user.id)
    validator = URLValidator() 
    a = []
    for i in qr_code:
        try:
            validator(f"{i.url}")
            url = i.url
            val = True
        except:
            url = i.url
            val = False
        a.append(
            {
                'id':i.id,
                'title':i.title,
                'url':url,
                'val':val,
                'qr_code':i.qr_code,
                'color':i.color,


                

            }
        )
    return render(request, 'home.html', {"form":form,"qr_code":a,'host':"https://qrcodeuz.herokuapp.com"} )

def delete(request,pk):
    model = YourModel.objects.get(pk=pk)
    model.delete()
    return redirect('home')


def loginPAGE(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            print(request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return redirect("home")
            else:
                messages.info(request,'invalid login')
                return redirect('login')
        else:
            return render(request,'login.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:    
        if request.method == 'POST':
            print(request.POST)
            req = request.POST
            first_name = req['first_name']
            username = req['username']
            email = req['email']
            password1 = req['password1']
            password2 = req['password2']
            if password1 ==password2:
                if User.objects.filter(username=username).exists():
                    messages.info(request,"User exists")
                    return redirect('register')
                elif User.objects.filter(email=email).exists():
                    messages.info(request,"Email exists")
                    return redirect('register')
                else:
                    user = User.objects.create_user(username=username,first_name=first_name,email=email,password=password1)
                    user.save()
                    return redirect('login')
            else:
                messages.info(request,"Password is match")
                return redirect('register')
        else:
            return render(request, 'register.html')



def logoutPAGE(request):
    logout(request)
    return redirect('login')


def pages(request,pk):
    data = YourModel.objects.get(pk=pk)
    return render(request, 'page.html',{"i":data})

templates/accounts/complete.html
<div style="
    display: flex;
    flex-direction: column;
    text-align: center;
    margin-top: 30vh;">
    
    <h3 style="margin-bottom: -.2em;">Password reset complete</h3>
    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'login' %}">Login</a>
</div>

templates/accounts/confirm.html
<div style="    display: flex;
flex-direction: column;
text-align: center;
margin-top: 25vh;">
    <h3>Enter new password</h3>
<p>Please enter your new password twice so we can verify you typed it in correctly.</p>
<form method="post">
    {% csrf_token %}
    <div>
        <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="Password">
    </div>
    <div  style="margin-top: 10px;">
        <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Confirm password">
    </div>
    <div  style="margin-top: 10px;">
        <button style="outline: none;
        overflow: hidden;
        border: none;
        padding:5px 10px;
        border-radius: 2px;
        background-color: black;
        color: white;
        cursor: pointer;" type="Submit" name="Update Password">Submit</button>
    </div>
</form>
</div>

templates/accounts/reset.html
<div style="    
display: flex;
margin: auto;
flex-direction: column;
text-align: center;
margin-top: 30vh;">
    <h3>Password reset</h3>

    <form method="post" >
        {% csrf_token %}
        <input type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" placeholder="Email">
        <div style="margin-top: 10px;">
            <button style="outline: none;
            overflow: hidden;
            border: none;
            padding:5px 10px;
            border-radius: 2px;
            background-color: black;
            color: white;
            cursor: pointer;" type="Submit" name="Send email">Submit</button>
            <!-- <input type="Submit" name="Send email"> -->
        </div>
        <div style="margin-top: 10px;">
            <button style="outline: none;
            overflow: hidden;
            border: none;
            padding:5px 10px;
            border-radius: 2px;
            background-color: black;
            color: white;
            cursor: pointer;" onclick="window.history.back()" >Go back</button>
        </div>

    </form> 
</div>

templates/accounts/reset_done.html
<div style="max-width: 40%;
text-align: center;
display: flex;
flex-direction: column;
margin: auto;
margin-top: 25vh;">
    <h2>Password reset sent</h2>
<h4>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</h4>
<h4>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h4>  
</div>

templates/home.html
<!DOCTYPE html>
{% load static %} {% load social_share %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      type="image/x-icon"
      href="https://i.ibb.co/PC5nXTH/g4g.png"
    />
    <title>Qr Code</title>
    <style>
      body {
        display: flex;
        align-items: center;
        flex-direction: column;
      }
      .bit {
        margin-top: 10px;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      .qr {
        border-radius: 5px;
        margin-top: 50px;
        display: flex;
        flex-direction: column;
        align-items: center;
        transition: 0.5s;
      }
      .qr:hover {
        box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
      }
      h1 {
        margin-top: 2px;
        margin: 0;
      }

      a {
        text-decoration: none;
        color: #fff;
      }
      .btn {
        padding: 5px 19px;
        margin-bottom: 10px;
        background-color: var(--color-button);
        border-radius: 5px;
        overflow: hidden;
        margin-right: 16px;
      }
      .btn1 {
        padding: 5px 10px;
        margin-bottom: 10px;
        background-color: var(--color-button);
        border-radius: 5px;
        overflow: hidden;
      }
      #id_title {
        outline: none;
        padding: 5px 10px;
      }
      #id_url {
        outline: none;
        padding: 5px 10px;
      }
      button {
        outline: none;
        overflow: hidden;
        border: none;
        padding: 5px 10px;
        border-radius: 2px;
        background-color: var(--color-button);
        color: white;
        cursor: pointer;
        
        }
        #id_color{
          -webkit-appearance: none;
          -moz-appearance: none;
          appearance: none;
          width: 200px;
          height: 35px;
          background-color: transparent;
          border: none;
          cursor: pointer;
        }
        #id_color::-webkit-color-swatch{
          border-radius:5px;
          border: none;
          
      }
    </style>
  </head>
  <body>
    <div
      style="
        display: block;
        margin-left: auto;
        margin-right: 34px;
        margin-top: 15px;
      "
    >
      Hello {{request.user.username}}  |  
      <a style="color: black" href="{% url 'logout' %}">LogOut</a>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="bit">
        <input
          type="text"
          name="title"
          required
          id="id_title"
          placeholder="Title"
        />
      </div>
      <div class="bit">
        <input
          type="text"
          name="url"
          required
          id="id_url"
          placeholder="Text or URL"
        />
      </div>
      <div class="bit">
        <input
          type="hidden"
          value="{{request.user.id}}"
          name="user"
          id="id_user"
        />
        <input type="hidden" name="qr_code" accept="image/*" id="id_qr_code" />
      </div>
     
      <input type="color" name="color" id="id_color" value="#000"/>

      <div class="bit">
        <button type="submit" style="--color-button: black">Submit</button>
      </div>
    </form>

    {% for i in qr_code %}

    <div class="qr">
      <h1 style="color: {{i.color}}">{{i.title}}</h1>
      {% if i.val is True %}
      <a target="_blank" href="{{i.url}}"
        ><img src="/media/{{i.qr_code}}" alt=""
      /></a>
      {% else %}
      <a href="{% url 'page' i.id %}"
        ><img src="/media/{{i.qr_code}}" alt=""
      /></a>
      {% endif %}
      <div style="margin-bottom: 10px; display: flex; text-align: center">
        <a
          class="btn"
          href="{% url 'delete' i.id %}"
          style="--color-button: {{ i.color }}; display: flex; align-items: center; justify-content: center;"
          >Delete</a
        >
        <!-- <a class="btn" href="https://t.me/share?url=http%3A%2F%2F9cfa-82-215-101-34.ngrok.io%2Fmedia%2Fqr_codes%2Fqr_code-dsf_1LAABIy.png&text=dfdf" style="border: 1px solid red;">
                share</a> -->
        <a
        class="tgme_widget_share_btn btn"
          style="display: flex; align-items: center; justify-content: center; background:{{i.color}}; padding:auto;"
          href="https://t.me/share?url={{host}}/media/{{i.qr_code}}"
          >
          <img
            style="width: 19   px; object-fit: cover;"
            src="https://telegram.org/img/WidgetButton_LogoSmall.png"
            alt=""
          />
          <span
            class="tgme_widget_share_label"
            target="_blank"
            >Share</span
          ></a
        >

        <!-- <script async src="{% static 'admin/index.js' %}" data-telegram-share-url="http://9cfa-82-215-101-34.ngrok.io/media/{{i.qr_code}}" data-comment="{{i.url}}" data-size="large"></script> -->
        <script>
          console.log(
            document.currentScript.previousElementSibling.parentElement.getElementsByTagName(
              "iframe"
            )[0]
          );
        </script>
      </div>
      <a
        class="btn1"
        download="{{i.title}}"
        href="/media/{{i.qr_code}}"
        style="--color-button: {{ i.color }}"
        >Download</a
      >
    </div>
    {% endfor %}
  </body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/PC5nXTH/g4g.png">
    <title>Login</title>
    <style>
        body{
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .main{
            display: flex;
            height: 95vh;
            
        }
        form{
            margin-top: 30vh;
        }
        .bit{
            
            margin-top: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .qr{
            border-radius: 5px;
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            align-items: center;
            transition: .5s;
        }
        .qr:hover{
            box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        }
        h1{
            margin-top: 2px;
            margin:0;
        }

        a{
            text-decoration: none;
            color: #000;
            display: flex;
            justify-content: center;
            text-decoration: underline;
            margin-top: 5px;

            
        }
        .btn{
            padding: 5px 10px;
            margin-bottom: 10px;
            background-color: black;
            border-radius: 2px;
            overflow: hidden;
        }
        button{
            outline: none;
            overflow: hidden;
            border: none;
            padding:5px 10px;
            border-radius: 2px;
            background-color: black;
            color: white;
            cursor: pointer;
        }
        .inputt{
            outline: none;
            padding: 5px 10px;
        }
    </style>
</head>
<body>
    <div class="main">
        <form action="" method="post">
            {% csrf_token %}
           <div class="bit">
                <input type="text" class="inputt" name="username" placeholder="Username">
           </div>
            <div class="bit">
                <input type="password" class="inputt" name="password" placeholder="Password">
            </div>
            <div class="bit">
                <button type="submit">Submit</button>
            </div>
            <div>
            <a href="{% url 'register' %}">register</a>
            </div>
            <div>
            <a href="{% url 'reset_password' %}">forgot password</a>
            </div>
            <div style="color: rgb(206, 10, 10); text-align: center;
            margin-top: 5px;">
                {% for message in messages %}
                {{message}}
                {% endfor %}
            </div>
        </div>
        </form>
        
    
</body>
</html>

templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <style>
        body{
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .bit{
            margin-top: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .qr{
            border-radius: 5px;
            margin-top: 20vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            transition: .5s;
        }
        .qr:hover{
            box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        }
        h1{
            margin-top: 2px;
            margin:0;
        }

        a{
            text-decoration: none;
            color: #fff;

            
        }
        .btn{
            padding: 5px 10px;
            margin-bottom: 10px;
            background-color: black;
            border-radius: 2px;
            overflow: hidden;
        }
        #id_title{
            outline: none;
            padding: 5px 10px;
        }
        #id_url{    
            outline: none;
            padding: 5px 10px;
        }
        button{
            outline: none;
            overflow: hidden;
            border: none;
            padding:5px 10px;
            border-radius: 2px;
            background-color: black;
            color: white;
            cursor: pointer;
        }
        
    </style>
</head>
<body>
    <div class="qr">
        <h1>{{i.title}}</h1>
        <img src="/media/{{i.qr_code}}" alt="">
        <p>{{i.url}}</p>
        <a class="btn" href="{% url 'delete' i.id %}">Delete</a>
        <a class="btn" download="{{i.title}}" href="/media/{{i.qr_code}}">Download</a>
    </div>
    <!-- <div style="margin-top: 10px;">
        <button style="outline: none;
        overflow: hidden;
        border: none;
        padding:5px 10px;
        border-radius: 2px;
        background-color: black;
        color: white;
        cursor: pointer;" onclick="window.history.back()" >Go back</button>
    </div> -->
    
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/PC5nXTH/g4g.png">
    <title>Register</title>
    <style>
        body{
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .main{
            display: flex;
            height: 95vh;
            
        }
        form{
            margin-top: 30vh;
        }
        .bit{
            
            margin-top: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .qr{
            border-radius: 5px;
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            align-items: center;
            transition: .5s;
        }
        .qr:hover{
            box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        }
        h1{
            margin-top: 2px;
            margin:0;
        }

        a{
            text-decoration: none;
            color: #000;
            display: flex;
            justify-content: center;
            text-decoration: underline;
            margin-top: 5px;

            
        }
        .btn{
            padding: 5px 10px;
            margin-bottom: 10px;
            background-color: black;
            border-radius: 2px;
            overflow: hidden;
        }
        #id_title{
            outline: none;
            padding: 5px 10px;
        }
        #id_url{    
            outline: none;
            padding: 5px 10px;
        }
        button{
            outline: none;
            overflow: hidden;
            border: none;
            padding:5px 10px;
            border-radius: 2px;
            background-color: black;
            color: white;
            cursor: pointer;
        }
        .share{
            color: black;
            margin-bottom: 5px;
        }
        .inputt{
            outline: none;
            padding: 5px 10px;
        }
    </style>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <div class="bit">
            <input type="text" class="inputt" name="first_name" placeholder="Name">
        </div>
        <div class="bit">
            <input type="text" class="inputt" name="username" placeholder="Username">
        </div>
        <div class="bit">
            <input type="email" class="inputt" name="email" placeholder="Email">
        </div>
        <div class="bit">
            <input type="password" class="inputt" name="password1" placeholder="Password">
        </div>
        <div class="bit">
            <input type="password" class="inputt" name="password2" placeholder="Confirm password">
        </div>
        <div class="bit">
            <button type="submit">Submit</button>
        </div>
        <div>
            <a href="{% url 'login' %}">login</a>
        </div>
        <div style="color: rgb(206, 10, 10); text-align: center;
        margin-top: 5px;">
                {% for message in messages %}
                {{message}}
                {% endfor %}
            </div>
    </form>
    
</body>
</html>